# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-27 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapshow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userevent',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userevent',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='userevent',
            name='event_type',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userevent',
            name='mail',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='userevent',
            name='name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='userevent',
            name='phone_number',
            field=models.CharField(default='', max_length=15),
        ),
    ]
