# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-27 16:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapshow', '0003_auto_20160527_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitorevent',
            name='name',
            field=models.TextField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='visitorevent',
            name='phone_number',
            field=models.TextField(default='', max_length=15),
        ),
    ]
